language: node_js

sudo: required

services:
    - docker

node_js:
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"

env:
    global:
        # DOCKER_USER
        - secure: "aGEHloFRoZSG27pzu5L5EeqBVautQGC+NSoFE5SYhx0n0y7OyRN9iqCCHyb3YsLjwDVx//ft6x70I+/Ob1qVE2LjG/uyAiDJa8KGWL3CpAQJp8ZeuKCpTBBSu5IOEECOMYNhIr/xihiZjwE0theCQ5Vm0KhMtLluGlInz293x2KLItzsCU4zzAg656G3LIQfUYHWym5Zcd5wCa6PUmEuojLl3hu6o88cWKx4pkigsFCQiehi+/8eGxwi0oU7RP9G1E5HqnIfZsowbjnRwDM7SvSh+Wyu1jK4H8SK7FVYerb6BCPWgSYY0ng9v5J4CoiFI/9K/SkEveAVTcQzGlVIwEJWBjZtK7sgyxsFSmvAHRgzJXyA19NMO02j+sbZLY8q1EyAj5WJaoEZpa6JghthqGRToutM2Oe2F9DgVGqVdgIsWniH3s7NvRPBDyNb2+rxjF1ux6Mpiy69jE5jo/eXBkvaZHKu2vjwUpTKSiEmF158psaBb4mOUwEBRxEwbXD6++O2HKONV9A1Ik8padf6O5wKo4wnyA6NhAQwMbEqSMQPF4eN0uE/b/YZoCvmR4YrPPmzPIXsQlRZxYvN7qm3zHL443+MFSEX/4xHhv5mn9uDpMhPHn6RgKkjI9ensZjpkJ89FWp/f4mnwb9tnj7KSOVdri6zQUT/rurUj0YMdPM="
        # DOCKER_PASS
        - secure: "ef/mPSe3aNCogBEd1/2Cnn7HK7Lz/sHXnVXwgWKwJcZC32r5c/79OH7HFY1RAZpAq/Iw0mdmiFrQ2yzlQiaV8Y9/tJnnEge0ueodtS38quiOb1USD88Qk8O7wuiiblnUTRTqWvn2H0yWqC+EpztvL23VxBLNSByNouiPa48B6u9j6hZfxhSMdw7HzdoxY2AIW04FKtMMOFZ0wCapsxtTG6N0EPDIW7tIs8VnsllRwbbe5DEvtLgEQx7C1XU1SSUCZa9x6vZHRUL6kvc6PRYdr7pVcHvHJIUT5kMdnQ7GsYvUH6sz/x4zX7nGOAqGgzIBtjShWBwbbu4sYnqupRFQTraAScGeDG1j1YUY/Vo2tQQ/ryZ2axR3ZC3HCmEvzVJ3mPBF3byUMLTTv1fqOHlpDBy83WXTSMw0eLoc/GWcHmvOjYpau0JrDLBJFeh6vB8G75AeswOiNbPOFKyvPiLowvFZ93uii9LDlxeb2Ls2OITJ0LgsSwogqyOBs3UEF3bpaJjwnuI4lH4VM+1hMW7FErLZiC0fggrDUat+FU/M4OaQgeN4QHm3mMGISq69oV+QP9OujTecQ/utCyjzIy4x7d+dJ7KBw4Gvg9AacHUJJtgYB8NldgrLW993c0nv/f1bbgc6a4zBl5kIPk+XhJ3jGwWNye3H9J/kRiChwORQCvk="
        - COMMIT=${TRAVIS_COMMIT::8}

cache:
    directories:
        - node_modules

script:
    - npm install
    - npm run cs
    - if [[ -z "$TRAVIS_TAG" && "$TRAVIS_BRANCH" == "master" ]]; then npm run changelog-lint; fi
    - npm run specs

deploy:
    - provider: script
      script: ci/deploy.sh
      on:
          node: 9
          all_branches: master
    - provider: script
      script: ci/deploy.sh
      on:
          node: 9
          tags: true
